FROM dockcross/base:latest
MAINTAINER Matt McCormick "matt.mccormick@kitware.com"

COPY sources.list /etc/apt/sources.list
RUN dpkg --add-architecture ppc64 ; apt-get update ; apt-get -y upgrade ; apt-get update ;

ENV CROSS_TRIPLE powerpc64-linux-gnu

RUN apt-get install -y \
  python-dev

#include "common.crosstool"

# enable sources for easy cross-compilation of packages
RUN echo 'deb-src http://deb.debian.org/debian/ oldstable main contrib non-free' >> /etc/apt/sources.list

# cross-compiled zlib
RUN apt-get update && apt-get source zlib1g-dev \
 && rm *.tar* *.dsc \
 && cd zlib* \
 && ./configure \
        --prefix /usr \
        --libdir /usr/lib/$(echo $CC --prefix /usr/ | sed -e 's/-gcc-.*//g') \
 && make -j \
 && make install \
 && cd .. \
 && rm -rf zlib* \
 && rm -rf /var/lib/apt/lists/*

# cross-compiled bzip
RUN apt-get update && apt-get source libbz2-dev \
 && rm *.tar* *.dsc \
 && cd bzip2* \
 && make install PREFIX=/usr/lib/${CROSS_TRIPLE} \
 && cd .. \
 && rm -rf bzip2* \
 && rm -rf /var/lib/apt/lists/*

# cross-compiled expat
RUN apt-get update && apt-get source libexpat1-dev \
 && rm *.tar* *.dsc \
 && cd expat* \
 && ./configure \
        --prefix /usr \
        --libdir /usr/lib/${CROSS_TRIPLE} \
 && make -j \
 && make install \
 && cd .. \
 && rm -rf expat* \
 && rm -rf /var/lib/apt/lists/*

# cross-compiled openssl
RUN apt-get update && apt-get source libssl-dev \
 && rm *.tar* *.dsc \
 && cd openssl* \
 && CC= AR= ./Configure linux-ppc64 \
        --prefix=$PWD/install \
 && make -j \
 && make install \
 && cp -R install/lib/* /usr/lib/${CROSS_TRIPLE} \
 && cd .. \
 && rm -rf openssl* \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

RUN apt-get install -y libglib2.0-dev zlib1g-dev libpixman-1-dev && \
  curl -L http://wiki.qemu-project.org/download/qemu-2.6.0.tar.bz2 | tar xj && \
  cd qemu-2.6.0 && \
  ./configure --target-list=ppc64-linux-user --prefix=/usr && \
  make -j$(nproc) && \
  make install && \
  cd .. && rm -rf qemu-2.6.0

ENV CROSS_ROOT ${XCC_PREFIX}/${CROSS_TRIPLE}
ENV AS=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-as \
    AR=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-ar \
    CC=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-gcc \
    CPP=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-cpp \
    CXX=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-g++ \
    LD=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-ld \
    FC=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-gfortran

ENV QEMU_LD_PREFIX "${CROSS_ROOT}/${CROSS_TRIPLE}/sysroot"
ENV QEMU_SET_ENV "LD_LIBRARY_PATH=${CROSS_ROOT}/lib:${QEMU_LD_PREFIX}"

WORKDIR /work

COPY Toolchain.cmake /usr/lib/${CROSS_TRIPLE}/
ENV CMAKE_TOOLCHAIN_FILE /usr/lib/${CROSS_TRIPLE}/Toolchain.cmake

ENV PKG_CONFIG_PATH /usr/lib/powerpc64le-linux-gnu/pkgconfig

# Linux kernel cross compilation variables
ENV PATH ${PATH}:${CROSS_ROOT}/bin
ENV CROSS_COMPILE ${CROSS_TRIPLE}-
ENV ARCH powerpc

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG IMAGE=dockcross/linux-ppc64
ARG VERSION=latest
ARG VCS_REF
ARG VCS_URL
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name=$IMAGE \
      org.label-schema.version=$VERSION \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
ENV DEFAULT_DOCKCROSS_IMAGE ${IMAGE}:${VERSION}

